### ISSUE TITLE
Install github checkout action to make your releases more secure 

### ISSUE THREAD

**Issue by 0xAverageUser** [wooorm/property-information#16]
along the lines of 
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Add additional steps for your job here

```
